/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_menu;

import javax.swing.JOptionPane;
import login_menu.LoginMenu;
import login_menu.Player;



/**
 *
 * @author Jorge
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        MyProfile_Pane.setVisible(false);
        Jugar_Ajedrez.setVisible(false);
        Configuraciones.setVisible(false);
        Reportes.setVisible(false);
        VerMisDatos.setVisible(false);
        CambiarPass.setVisible(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu_Pane = new javax.swing.JLayeredPane();
        btn_config = new javax.swing.JButton();
        btn_jugar = new javax.swing.JButton();
        btn_perfil = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        btn_cerrarsesion = new javax.swing.JButton();
        MyProfile_Pane = new javax.swing.JLayeredPane();
        btn_verjuegos = new javax.swing.JButton();
        btn_verdatos = new javax.swing.JButton();
        btn_cambiarpass = new javax.swing.JButton();
        btn_conectarfb = new javax.swing.JButton();
        btn_eliminarcuenta = new javax.swing.JButton();
        btn_regresarmenuprincipal = new javax.swing.JButton();
        Jugar_Ajedrez = new javax.swing.JLayeredPane();
        btn_partidanueva = new javax.swing.JButton();
        btn_cargarpartida = new javax.swing.JButton();
        btn_eliminarpartida = new javax.swing.JButton();
        btn_transferir = new javax.swing.JButton();
        btn_regresaramenup = new javax.swing.JButton();
        Reportes = new javax.swing.JLayeredPane();
        btn_ranking = new javax.swing.JButton();
        btn_ultimosjuegos = new javax.swing.JButton();
        btn_regresaralmenup = new javax.swing.JButton();
        Configuraciones = new javax.swing.JLayeredPane();
        btn_ModoTutorial = new javax.swing.JButton();
        btn_EstablecerTiempo = new javax.swing.JButton();
        btn_Regresaralmenup = new javax.swing.JButton();
        VerMisDatos = new javax.swing.JLayeredPane();
        verUsuario = new javax.swing.JTextField();
        verPuntos = new javax.swing.JTextField();
        verPartidasPendientes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_regresaraperfil = new javax.swing.JButton();
        CambiarPass = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        btn_newPass = new javax.swing.JButton();
        txtnewPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_config.setText("Configuraciones");
        btn_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configActionPerformed(evt);
            }
        });

        btn_jugar.setText("Jugar Ajedrez");
        btn_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jugarActionPerformed(evt);
            }
        });

        btn_perfil.setText("Mi Perfil");
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });

        btn_reportes.setText("Reportes");
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_cerrarsesion.setText("Cerrar Sesión");
        btn_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenu_PaneLayout = new javax.swing.GroupLayout(MainMenu_Pane);
        MainMenu_Pane.setLayout(MainMenu_PaneLayout);
        MainMenu_PaneLayout.setHorizontalGroup(
            MainMenu_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenu_PaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenu_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_jugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );
        MainMenu_PaneLayout.setVerticalGroup(
            MainMenu_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenu_PaneLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(btn_jugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_config)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cerrarsesion)
                .addGap(60, 60, 60))
        );
        MainMenu_Pane.setLayer(btn_config, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainMenu_Pane.setLayer(btn_jugar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainMenu_Pane.setLayer(btn_perfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainMenu_Pane.setLayer(btn_reportes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainMenu_Pane.setLayer(btn_cerrarsesion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(MainMenu_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        MyProfile_Pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_verjuegos.setText("Ver Mis Ultimos Juegos");
        btn_verjuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verjuegosActionPerformed(evt);
            }
        });
        MyProfile_Pane.add(btn_verjuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 86, 209, -1));

        btn_verdatos.setText("Ver Mis Datos");
        btn_verdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verdatosActionPerformed(evt);
            }
        });
        MyProfile_Pane.add(btn_verdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 51, 209, -1));

        btn_cambiarpass.setText("Cambiar Mi Contraseña");
        btn_cambiarpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiarpassActionPerformed(evt);
            }
        });
        MyProfile_Pane.add(btn_cambiarpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 121, 209, -1));

        btn_conectarfb.setText("Conectar a Facebook");
        MyProfile_Pane.add(btn_conectarfb, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 156, 209, -1));

        btn_eliminarcuenta.setText("Eliminar Mi Cuenta");
        btn_eliminarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarcuentaActionPerformed(evt);
            }
        });
        MyProfile_Pane.add(btn_eliminarcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 191, 209, -1));

        btn_regresarmenuprincipal.setText("Regresar al Menu Principal");
        btn_regresarmenuprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarmenuprincipalActionPerformed(evt);
            }
        });
        MyProfile_Pane.add(btn_regresarmenuprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 226, 220, -1));

        getContentPane().add(MyProfile_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        btn_partidanueva.setText("Partida Nueva");

        btn_cargarpartida.setText("Cargar Partida");

        btn_eliminarpartida.setText("Eliminar Partida");

        btn_transferir.setText("Transferir");

        btn_regresaramenup.setText("Regresar al Menu Principal");
        btn_regresaramenup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaramenupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jugar_AjedrezLayout = new javax.swing.GroupLayout(Jugar_Ajedrez);
        Jugar_Ajedrez.setLayout(Jugar_AjedrezLayout);
        Jugar_AjedrezLayout.setHorizontalGroup(
            Jugar_AjedrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugar_AjedrezLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(Jugar_AjedrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_regresaramenup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_transferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarpartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cargarpartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_partidanueva, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        Jugar_AjedrezLayout.setVerticalGroup(
            Jugar_AjedrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugar_AjedrezLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_partidanueva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cargarpartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminarpartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresaramenup)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Jugar_Ajedrez.setLayer(btn_partidanueva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jugar_Ajedrez.setLayer(btn_cargarpartida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jugar_Ajedrez.setLayer(btn_eliminarpartida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jugar_Ajedrez.setLayer(btn_transferir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jugar_Ajedrez.setLayer(btn_regresaramenup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(Jugar_Ajedrez, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        btn_ranking.setText("Ranking");

        btn_ultimosjuegos.setText("Ultimos juegos globales");

        btn_regresaralmenup.setText("Regresar al menu principal");
        btn_regresaralmenup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaralmenupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportesLayout = new javax.swing.GroupLayout(Reportes);
        Reportes.setLayout(ReportesLayout);
        ReportesLayout.setHorizontalGroup(
            ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportesLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_regresaralmenup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ultimosjuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        ReportesLayout.setVerticalGroup(
            ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportesLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(btn_ranking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ultimosjuegos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresaralmenup)
                .addGap(69, 69, 69))
        );
        Reportes.setLayer(btn_ranking, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Reportes.setLayer(btn_ultimosjuegos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Reportes.setLayer(btn_regresaralmenup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        btn_ModoTutorial.setText("Modo Tutorial");

        btn_EstablecerTiempo.setText("Establecer Tiempo");

        btn_Regresaralmenup.setText("Regresar al menu principal");
        btn_Regresaralmenup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresaralmenupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfiguracionesLayout = new javax.swing.GroupLayout(Configuraciones);
        Configuraciones.setLayout(ConfiguracionesLayout);
        ConfiguracionesLayout.setHorizontalGroup(
            ConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfiguracionesLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(ConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Regresaralmenup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EstablecerTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ModoTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        ConfiguracionesLayout.setVerticalGroup(
            ConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfiguracionesLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btn_ModoTutorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EstablecerTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Regresaralmenup)
                .addGap(63, 63, 63))
        );
        Configuraciones.setLayer(btn_ModoTutorial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Configuraciones.setLayer(btn_EstablecerTiempo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Configuraciones.setLayer(btn_Regresaralmenup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(Configuraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        verUsuario.setEditable(false);

        verPuntos.setEditable(false);
        verPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPuntosActionPerformed(evt);
            }
        });

        verPartidasPendientes.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Puntos Conseguidos:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Partidas Pendientes:");

        btn_regresaraperfil.setText("Regresar a Mi Perfil");
        btn_regresaraperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaraperfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerMisDatosLayout = new javax.swing.GroupLayout(VerMisDatos);
        VerMisDatos.setLayout(VerMisDatosLayout);
        VerMisDatosLayout.setHorizontalGroup(
            VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerMisDatosLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(verUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(verPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(verPartidasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_regresaraperfil)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        VerMisDatosLayout.setVerticalGroup(
            VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerMisDatosLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(verUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(verPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(VerMisDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerMisDatosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(verPartidasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresaraperfil)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        VerMisDatos.setLayer(verUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(verPuntos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(verPartidasPendientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        VerMisDatos.setLayer(btn_regresaraperfil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(VerMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Ingresar contraseña nueva:");

        btn_newPass.setText("Cambiar contraseña");
        btn_newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CambiarPassLayout = new javax.swing.GroupLayout(CambiarPass);
        CambiarPass.setLayout(CambiarPassLayout);
        CambiarPassLayout.setHorizontalGroup(
            CambiarPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CambiarPassLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(CambiarPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_newPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnewPass))
                .addGap(98, 98, 98))
        );
        CambiarPassLayout.setVerticalGroup(
            CambiarPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarPassLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtnewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_newPass)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        CambiarPass.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CambiarPass.setLayer(btn_newPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CambiarPass.setLayer(txtnewPass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(CambiarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsesionActionPerformed
       LoginMenu LogIn = new LoginMenu();
        MainMenu_Pane.setVisible(false); 
        LogIn.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btn_cerrarsesionActionPerformed

    private void btn_regresarmenuprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarmenuprincipalActionPerformed
        MyProfile_Pane.setVisible(false);
        MainMenu_Pane.setVisible(true);   
    }//GEN-LAST:event_btn_regresarmenuprincipalActionPerformed

    private void btn_regresaramenupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaramenupActionPerformed
        Jugar_Ajedrez.setVisible(false);
        MainMenu_Pane.setVisible(true);
    }//GEN-LAST:event_btn_regresaramenupActionPerformed

    private void btn_regresaralmenupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaralmenupActionPerformed
        Reportes.setVisible(false);
        MainMenu_Pane.setVisible(true);
    }//GEN-LAST:event_btn_regresaralmenupActionPerformed

    private void btn_RegresaralmenupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresaralmenupActionPerformed
        Configuraciones.setVisible(false);
        MainMenu_Pane.setVisible(true);
    }//GEN-LAST:event_btn_RegresaralmenupActionPerformed

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
        MainMenu_Pane.setVisible(false);
        MyProfile_Pane.setVisible(true);
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jugarActionPerformed
        MainMenu_Pane.setVisible(false);
        Jugar_Ajedrez.setVisible(true);
    }//GEN-LAST:event_btn_jugarActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        MainMenu_Pane.setVisible(false);
        Reportes.setVisible(true);
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configActionPerformed
        MainMenu_Pane.setVisible(false);
        Configuraciones.setVisible(true);
    }//GEN-LAST:event_btn_configActionPerformed

    private void btn_verjuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verjuegosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verjuegosActionPerformed

    private void btn_verdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verdatosActionPerformed
        VerMisDatos.setVisible(true);
        MyProfile_Pane.setVisible(false);
        verUsuario.setText(""+LoginMenu.currentPlayer.getUsername());
        verPuntos.setText(""+LoginMenu.currentPlayer.getPoints());
        verPartidasPendientes.setText("0");
    }//GEN-LAST:event_btn_verdatosActionPerformed

    private void verPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verPuntosActionPerformed

    private void btn_regresaraperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaraperfilActionPerformed
      VerMisDatos.setVisible(false);
      MyProfile_Pane.setVisible(true);
        
    }//GEN-LAST:event_btn_regresaraperfilActionPerformed

    private void btn_newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newPassActionPerformed
        
        if(txtnewPass.getPassword().length ==0){
            JOptionPane.showMessageDialog(null, "Porfavor ingrese nueva contraseña!!");
        }
        if(txtnewPass.getPassword().length>5){
            JOptionPane.showMessageDialog(null, "Contraseña no puede ser mayor de 5 caracteres!!");
            txtnewPass.setText("");       
        }else{       
        int r = JOptionPane.showConfirmDialog(null, "Esta seguro de cambiar la contraseña?", "Cambiar Contraseña", JOptionPane.YES_NO_OPTION);
            if(r == JOptionPane.YES_OPTION){
               LoginMenu.currentPlayer.setPassword(String.valueOf(txtnewPass.getPassword()));
               txtnewPass.setText("");
               CambiarPass.setVisible(false);
               MyProfile_Pane.setVisible(true);
        }else{
            txtnewPass.setText("");
            CambiarPass.setVisible(false);
            MyProfile_Pane.setVisible(true);
            
        }
       }
    }//GEN-LAST:event_btn_newPassActionPerformed

    private void btn_cambiarpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiarpassActionPerformed
        MyProfile_Pane.setVisible(false);
        CambiarPass.setVisible(true);
    }//GEN-LAST:event_btn_cambiarpassActionPerformed

    private void btn_eliminarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarcuentaActionPerformed
    LoginMenu LogIn = new LoginMenu();
    int sure = JOptionPane.showConfirmDialog(null, "Esta seguro en eliminar cuenta?", "Eliminar Cuenta", JOptionPane.YES_NO_OPTION);
        if(sure == JOptionPane.YES_OPTION){
            Player.players.remove(LoginMenu.currentPlayer);
            JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente!!");
            
            MyProfile_Pane.setVisible(false);
            MainMenu_Pane.setVisible(false);
            LogIn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_eliminarcuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane CambiarPass;
    private javax.swing.JLayeredPane Configuraciones;
    private javax.swing.JLayeredPane Jugar_Ajedrez;
    private javax.swing.JLayeredPane MainMenu_Pane;
    private javax.swing.JLayeredPane MyProfile_Pane;
    private javax.swing.JLayeredPane Reportes;
    public javax.swing.JLayeredPane VerMisDatos;
    private javax.swing.JButton btn_EstablecerTiempo;
    private javax.swing.JButton btn_ModoTutorial;
    private javax.swing.JButton btn_Regresaralmenup;
    private javax.swing.JButton btn_cambiarpass;
    private javax.swing.JButton btn_cargarpartida;
    private javax.swing.JButton btn_cerrarsesion;
    private javax.swing.JButton btn_conectarfb;
    private javax.swing.JButton btn_config;
    private javax.swing.JButton btn_eliminarcuenta;
    private javax.swing.JButton btn_eliminarpartida;
    private javax.swing.JButton btn_jugar;
    private javax.swing.JButton btn_newPass;
    private javax.swing.JButton btn_partidanueva;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JButton btn_ranking;
    private javax.swing.JButton btn_regresaralmenup;
    private javax.swing.JButton btn_regresaramenup;
    private javax.swing.JButton btn_regresaraperfil;
    private javax.swing.JButton btn_regresarmenuprincipal;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JButton btn_transferir;
    private javax.swing.JButton btn_ultimosjuegos;
    private javax.swing.JButton btn_verdatos;
    private javax.swing.JButton btn_verjuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtnewPass;
    private javax.swing.JTextField verPartidasPendientes;
    private javax.swing.JTextField verPuntos;
    private javax.swing.JTextField verUsuario;
    // End of variables declaration//GEN-END:variables
}
