/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiPerfil;

/**
 *
 * @author samuelborjas
 */
public class MiPerfil extends javax.swing.JFrame {

    /**
     * Creates new form MiPerfil
     */
    public MiPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmdRegresarMP = new javax.swing.JButton();
        cmdFacebook = new javax.swing.JButton();
        cmdCambiarPass = new javax.swing.JButton();
        cmdVerDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mi Perfil");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmdRegresarMP.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        cmdRegresarMP.setText("Regresar Menu Principal");
        getContentPane().add(cmdRegresarMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        cmdFacebook.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        cmdFacebook.setText("Conectar a Facebook");
        getContentPane().add(cmdFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 230, -1));

        cmdCambiarPass.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        cmdCambiarPass.setText("Cambiar mi Contraseña");
        cmdCambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarPassActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCambiarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, -1));

        cmdVerDatos.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        cmdVerDatos.setText("Ver mis datos");
        cmdVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerDatosActionPerformed(evt);
            }
        });
        getContentPane().add(cmdVerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, -1));

        jLabel1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/VisualAssets/perfil.jpg"))); // NOI18N
        jLabel1.setText("Mi Perfil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerDatosActionPerformed
       VerDatos vd = new VerDatos();
        vd.setVisible(true);
    }//GEN-LAST:event_cmdVerDatosActionPerformed

    private void cmdCambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarPassActionPerformed
        CambiarPass cp = new CambiarPass();
            cp.setVisible(true);
    }//GEN-LAST:event_cmdCambiarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiarPass;
    private javax.swing.JButton cmdFacebook;
    private javax.swing.JButton cmdRegresarMP;
    private javax.swing.JButton cmdVerDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
