/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

import java.io.IOException;

/**
 *
 * @author Roberto Melara
 */
public class Batallas extends javax.swing.JFrame {

    /**
     * Creates new form Batallas
     */
    public Batallas() {
        initComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelSoldier1 = new javax.swing.JLabel();
        jLabelSoldier2 = new javax.swing.JLabel();
        jLabelSoldier3 = new javax.swing.JLabel();
        jLabelGondor = new javax.swing.JLabel();
        jLabelMordor = new javax.swing.JLabel();
        jLabelBattles = new javax.swing.JLabel();
        jLabelActiveTxt = new javax.swing.JLabel();
        jLabelRecordTxt = new javax.swing.JLabel();
        jLabelGondorTxt = new javax.swing.JLabel();
        jLabelMordorTxt = new javax.swing.JLabel();
        jLabelPlayedTxt = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelPlayedUser = new javax.swing.JLabel();
        jLabelPlayedGlobally = new javax.swing.JLabel();
        jLabelActiveUsers = new javax.swing.JLabel();
        jLabelHistoricUsers = new javax.swing.JLabel();
        jLabelGondorUser = new javax.swing.JLabel();
        jLabelGondorGlobally = new javax.swing.JLabel();
        jLabelTxt1 = new javax.swing.JLabel();
        jLabelTxt2 = new javax.swing.JLabel();
        jLabelTxt3 = new javax.swing.JLabel();
        jLabelTxt4 = new javax.swing.JLabel();
        jLabelTxt5 = new javax.swing.JLabel();
        jLabelMordorUser = new javax.swing.JLabel();
        jLabelMordorGlobbally = new javax.swing.JLabel();
        jLabelTxt6 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Batallas");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTittle.setFont(new java.awt.Font("Ringbearer", 0, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTittle.setText("Batallas");
        getContentPane().add(jLabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelSoldier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Medieval_Infantry.png"))); // NOI18N
        getContentPane().add(jLabelSoldier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabelSoldier2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Medieval_Infantry.png"))); // NOI18N
        getContentPane().add(jLabelSoldier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelSoldier3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Medieval_Infantry.png"))); // NOI18N
        getContentPane().add(jLabelSoldier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabelGondor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/FuerzasBien.png"))); // NOI18N
        getContentPane().add(jLabelGondor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabelMordor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/FuerzasMal.png"))); // NOI18N
        getContentPane().add(jLabelMordor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabelBattles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/BatallasHistoricas.png"))); // NOI18N
        getContentPane().add(jLabelBattles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabelActiveTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelActiveTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelActiveTxt.setText("Usuarios Activos:");
        getContentPane().add(jLabelActiveTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabelRecordTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelRecordTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRecordTxt.setText("Usuarios Historicos: ");
        getContentPane().add(jLabelRecordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabelGondorTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelGondorTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelGondorTxt.setText("Partidas Gondor:");
        getContentPane().add(jLabelGondorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabelMordorTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelMordorTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelMordorTxt.setText("Partidas Mordor");
        getContentPane().add(jLabelMordorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabelPlayedTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelPlayedTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelPlayedTxt.setText("Partidas Jugadas: ");
        getContentPane().add(jLabelPlayedTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabelRegresar.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRegresar.setText("Regresar");
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jLabelPlayedUser.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelPlayedUser.setForeground(new java.awt.Color(185, 167, 129));
        jLabelPlayedUser.setText("0");
        getContentPane().add(jLabelPlayedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabelPlayedGlobally.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelPlayedGlobally.setForeground(new java.awt.Color(185, 167, 129));
        jLabelPlayedGlobally.setText("0");
        getContentPane().add(jLabelPlayedGlobally, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        jLabelActiveUsers.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelActiveUsers.setText("0");
        getContentPane().add(jLabelActiveUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabelHistoricUsers.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelHistoricUsers.setForeground(new java.awt.Color(185, 167, 129));
        jLabelHistoricUsers.setText("0");
        getContentPane().add(jLabelHistoricUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabelGondorUser.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelGondorUser.setForeground(new java.awt.Color(185, 167, 129));
        jLabelGondorUser.setText("0");
        getContentPane().add(jLabelGondorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabelGondorGlobally.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelGondorGlobally.setForeground(new java.awt.Color(185, 167, 129));
        jLabelGondorGlobally.setText("0");
        getContentPane().add(jLabelGondorGlobally, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabelTxt1.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt1.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt1.setText("Usuario");
        getContentPane().add(jLabelTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabelTxt2.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt2.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt2.setText("Global");
        getContentPane().add(jLabelTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jLabelTxt3.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt3.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt3.setText("Usuario");
        getContentPane().add(jLabelTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabelTxt4.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt4.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt4.setText("Global");
        getContentPane().add(jLabelTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jLabelTxt5.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt5.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt5.setText("Usuario");
        getContentPane().add(jLabelTxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabelMordorUser.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelMordorUser.setForeground(new java.awt.Color(185, 167, 129));
        jLabelMordorUser.setText("0");
        getContentPane().add(jLabelMordorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jLabelMordorGlobbally.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelMordorGlobbally.setForeground(new java.awt.Color(185, 167, 129));
        jLabelMordorGlobbally.setText("0");
        getContentPane().add(jLabelMordorGlobbally, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        jLabelTxt6.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt6.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt6.setText("Global");
        getContentPane().add(jLabelTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Estadisticas.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        //Regresar a el Menu de Tierra Media.
        TierraMedia tm = new TierraMedia();
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegresarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batallas().setVisible(true);
            }
        });
    }
    
    public void setValues(){
        try {
            jLabelPlayedUser.setText("" + MainMenu.Player1.partidas);
            jLabelPlayedGlobally.setText("" + Player.PartidasHistoricas());
            jLabelActiveUsers.setText("" + Player.Activos());
            jLabelHistoricUsers.setText("" + Player.Historicos());
            jLabelGondorUser.setText("" + MainMenu.Player1.fuerzaBien);
            jLabelGondorGlobally.setText("" + Player.FBHistoricas());
            jLabelMordorUser.setText("" + MainMenu.Player1.fuerzaMal);
            jLabelMordorGlobbally.setText("" + Player.FMHistoricas());
        } catch (IOException ex) {}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelActiveTxt;
    private javax.swing.JLabel jLabelActiveUsers;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBattles;
    private javax.swing.JLabel jLabelGondor;
    private javax.swing.JLabel jLabelGondorGlobally;
    private javax.swing.JLabel jLabelGondorTxt;
    private javax.swing.JLabel jLabelGondorUser;
    private javax.swing.JLabel jLabelHistoricUsers;
    private javax.swing.JLabel jLabelMordor;
    private javax.swing.JLabel jLabelMordorGlobbally;
    private javax.swing.JLabel jLabelMordorTxt;
    private javax.swing.JLabel jLabelMordorUser;
    private javax.swing.JLabel jLabelPlayedGlobally;
    private javax.swing.JLabel jLabelPlayedTxt;
    private javax.swing.JLabel jLabelPlayedUser;
    private javax.swing.JLabel jLabelRecordTxt;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelSoldier1;
    private javax.swing.JLabel jLabelSoldier2;
    private javax.swing.JLabel jLabelSoldier3;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelTxt1;
    private javax.swing.JLabel jLabelTxt2;
    private javax.swing.JLabel jLabelTxt3;
    private javax.swing.JLabel jLabelTxt4;
    private javax.swing.JLabel jLabelTxt5;
    private javax.swing.JLabel jLabelTxt6;
    // End of variables declaration//GEN-END:variables
}
