/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

/**
 *
 * @author Roberto Melara
 */
public class CambiarPass extends javax.swing.JFrame {

    /**
     * Creates new form CambiarPass
     */
    public CambiarPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelTxt1 = new javax.swing.JLabel();
        jLabelLabel = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jTextFieldActual = new javax.swing.JTextField();
        jTextFieldNuevo = new javax.swing.JTextField();
        jLabelTxt2 = new javax.swing.JLabel();
        jLabelWarning = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cambiar Password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTittle.setFont(new java.awt.Font("Ringbearer", 0, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTittle.setText("Cambiar Password");
        getContentPane().add(jLabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabelTxt1.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt1.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt1.setText("Actual:");
        getContentPane().add(jLabelTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabelLabel.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelLabel.setForeground(new java.awt.Color(185, 167, 129));
        jLabelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/pass.png"))); // NOI18N
        jLabelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLabelMousePressed(evt);
            }
        });
        getContentPane().add(jLabelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabelRegresar.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRegresar.setText("Regresar");
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));
        getContentPane().add(jTextFieldActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 100, -1));
        getContentPane().add(jTextFieldNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 100, -1));

        jLabelTxt2.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelTxt2.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTxt2.setText("Nuevo:");
        getContentPane().add(jLabelTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabelWarning.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(185, 167, 129));
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 520, 30));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/MiPerfilSub.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        //Regresar al menu mi perfil.
        MiPerfil mp = new MiPerfil();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegresarMousePressed

    private void jLabelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLabelMousePressed
        // Validar que el pass este correcto.
        if(jTextFieldActual.getText().equals(MainMenu.Player1.password)){
            if(jTextFieldNuevo.getText().length() > 5){
                jLabelWarning.setText("Password nuevo demasiado largo.");
            }else if(jTextFieldNuevo.getText().length() < 5){
                jLabelWarning.setText("Password nuevo demasiado corto.");
            }else{
                MainMenu.Player1.password = jTextFieldNuevo.getText();
                jLabelWarning.setText("Password se cambio con exito.");
            }
        }else{
            jLabelWarning.setText("Password actual no coincide.");
        }
    }//GEN-LAST:event_jLabelLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelLabel;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelTxt1;
    private javax.swing.JLabel jLabelTxt2;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JTextField jTextFieldActual;
    private javax.swing.JTextField jTextFieldNuevo;
    // End of variables declaration//GEN-END:variables
}
