/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

import java.io.IOException;

/**
 *
 * @author Roberto Melara
 */
public class MainMenu extends javax.swing.JFrame {
    static Player Player1;
    static Player Player2;
    static String ModoJuego = "TUTORIAL";
    

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        jLabelSignedInUser.setText(Player1.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSignedInAs = new javax.swing.JLabel();
        jLabelSignedInUser = new javax.swing.JLabel();
        jLabelPlay = new javax.swing.JLabel();
        jLabelMiddleEarth = new javax.swing.JLabel();
        jLabelMyProfile = new javax.swing.JLabel();
        jLabelSettings = new javax.swing.JLabel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lord of the Rings Stratego");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSignedInAs.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelSignedInAs.setForeground(new java.awt.Color(185, 167, 129));
        jLabelSignedInAs.setText("Signed In as:");
        getContentPane().add(jLabelSignedInAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelSignedInUser.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelSignedInUser.setForeground(new java.awt.Color(185, 167, 129));
        getContentPane().add(jLabelSignedInUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 300, 40));
        getContentPane().add(jLabelPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 214, 340, 390));

        jLabelMiddleEarth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMiddleEarthMousePressed(evt);
            }
        });
        getContentPane().add(jLabelMiddleEarth, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 150, 150));

        jLabelMyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMyProfileMousePressed(evt);
            }
        });
        getContentPane().add(jLabelMyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 234, 120, 240));

        jLabelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSettingsMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 190, 140));

        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMousePressed(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 660, 210, 80));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/MainMenuIcons.png"))); // NOI18N
        jLabelBackground.setInheritsPopupMenu(false);
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMousePressed
        try {
            //Cerrar Sesion.
            Player.guardar(Player1.username);
            Player1 = null;
            Inicio init = new Inicio();
            init.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            System.out.println(ex);}
    }//GEN-LAST:event_jLabelCerrarSesionMousePressed

    private void jLabelSettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSettingsMousePressed
        // Abrir el menu de Configuracion.
        Configuracion config = new Configuracion();
        config.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSettingsMousePressed

    private void jLabelMiddleEarthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiddleEarthMousePressed
        TierraMedia tm = new TierraMedia();
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelMiddleEarthMousePressed

    private void jLabelMyProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMyProfileMousePressed
        //Ir a mi perfil.
        MiPerfil mp = new MiPerfil();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelMyProfileMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelMiddleEarth;
    private javax.swing.JLabel jLabelMyProfile;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JLabel jLabelSignedInAs;
    private javax.swing.JLabel jLabelSignedInUser;
    // End of variables declaration//GEN-END:variables
}
