/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

/**
 *
 * @author Roberto Melara
 */
public class MiPerfil extends javax.swing.JFrame {

    /**
     * Creates new form MiPerfil
     */
    public MiPerfil() {
        initComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPuntos = new javax.swing.JLabel();
        jLabelGondor = new javax.swing.JLabel();
        jLabelPartidas = new javax.swing.JLabel();
        jLabelMordor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10Partida = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9Partida = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8Partida = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7Partida = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6Partida = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5Partida = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4Partida = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3Partida = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1Partida = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2Partida = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelDesactivarCuenta = new javax.swing.JLabel();
        jLabelCambiarCuenta = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mi Perfil");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTittle.setFont(new java.awt.Font("Ringbearer", 0, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTittle.setText("Mi Perfil");
        getContentPane().add(jLabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(185, 167, 129));
        jLabel1.setText("Username: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabelUser.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(185, 167, 129));
        jLabelUser.setText("-");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 240, 30));

        jLabel3.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(185, 167, 129));
        jLabel3.setText("Puntos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(185, 167, 129));
        jLabel4.setText("Partidas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(185, 167, 129));
        jLabel5.setText("Mordor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(185, 167, 129));
        jLabel6.setText("Gondor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabelPuntos.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelPuntos.setForeground(new java.awt.Color(185, 167, 129));
        jLabelPuntos.setText("-");
        getContentPane().add(jLabelPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 30, -1));

        jLabelGondor.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelGondor.setForeground(new java.awt.Color(185, 167, 129));
        jLabelGondor.setText("-");
        getContentPane().add(jLabelGondor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 20, -1));

        jLabelPartidas.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelPartidas.setForeground(new java.awt.Color(185, 167, 129));
        jLabelPartidas.setText("-");
        getContentPane().add(jLabelPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 20, -1));

        jLabelMordor.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelMordor.setForeground(new java.awt.Color(185, 167, 129));
        jLabelMordor.setText("-");
        getContentPane().add(jLabelMordor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 20, -1));

        jLabel11.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(185, 167, 129));
        jLabel11.setText("Ultimas 10 Partidas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(185, 167, 129));
        jLabel12.setText("1.-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel10Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel10Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel10Partida.setText("-");
        getContentPane().add(jLabel10Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 420, -1));

        jLabel14.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(185, 167, 129));
        jLabel14.setText("2.-");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel9Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel9Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel9Partida.setText("-");
        getContentPane().add(jLabel9Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 420, -1));

        jLabel16.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(185, 167, 129));
        jLabel16.setText("3.-");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel8Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel8Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel8Partida.setText("-");
        getContentPane().add(jLabel8Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 420, -1));

        jLabel18.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(185, 167, 129));
        jLabel18.setText("4.-");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel7Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel7Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel7Partida.setText("-");
        getContentPane().add(jLabel7Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 420, -1));

        jLabel20.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(185, 167, 129));
        jLabel20.setText("5.-");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel6Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel6Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel6Partida.setText("-");
        getContentPane().add(jLabel6Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 420, -1));

        jLabel22.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(185, 167, 129));
        jLabel22.setText("6.-");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel5Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel5Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel5Partida.setText("-");
        getContentPane().add(jLabel5Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 420, -1));

        jLabel24.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(185, 167, 129));
        jLabel24.setText("7.-");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel4Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel4Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel4Partida.setText("-");
        getContentPane().add(jLabel4Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 420, -1));

        jLabel26.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(185, 167, 129));
        jLabel26.setText("8.-");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel3Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel3Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel3Partida.setText("-");
        getContentPane().add(jLabel3Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 420, -1));

        jLabel28.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(185, 167, 129));
        jLabel28.setText("9.-");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jLabel1Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel1Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel1Partida.setText("-");
        getContentPane().add(jLabel1Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 420, -1));

        jLabel30.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(185, 167, 129));
        jLabel30.setText("10.-");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabel2Partida.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel2Partida.setForeground(new java.awt.Color(185, 167, 129));
        jLabel2Partida.setText("-");
        getContentPane().add(jLabel2Partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 420, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Medieval_Infantry.png"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/puntos.png"))); // NOI18N
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 100));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/BatallasHistoricas.png"))); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/bin.png"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/pass.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabelDesactivarCuenta.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelDesactivarCuenta.setForeground(new java.awt.Color(185, 167, 129));
        jLabelDesactivarCuenta.setText("Desactivar Cuenta");
        jLabelDesactivarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDesactivarCuentaMousePressed(evt);
            }
        });
        getContentPane().add(jLabelDesactivarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabelCambiarCuenta.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelCambiarCuenta.setForeground(new java.awt.Color(185, 167, 129));
        jLabelCambiarCuenta.setText("Cambiar Password");
        jLabelCambiarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCambiarCuentaMousePressed(evt);
            }
        });
        getContentPane().add(jLabelCambiarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        jLabelRegresar.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRegresar.setText("Regresar");
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Submenus_Background1.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        // Regresar al menu principal.
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegresarMousePressed

    private void jLabelCambiarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCambiarCuentaMousePressed
        //Ir a cambiar pass.
        CambiarPass cp = new CambiarPass();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelCambiarCuentaMousePressed

    private void jLabelDesactivarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDesactivarCuentaMousePressed
        //Ir a eliminar cuenta.
        EliminarCuenta ec = new EliminarCuenta();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelDesactivarCuentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10Partida;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel1Partida;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel2Partida;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel3Partida;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Partida;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5Partida;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6Partida;
    private javax.swing.JLabel jLabel7Partida;
    private javax.swing.JLabel jLabel8Partida;
    private javax.swing.JLabel jLabel9Partida;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCambiarCuenta;
    private javax.swing.JLabel jLabelDesactivarCuenta;
    private javax.swing.JLabel jLabelGondor;
    private javax.swing.JLabel jLabelMordor;
    private javax.swing.JLabel jLabelPartidas;
    private javax.swing.JLabel jLabelPuntos;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabelUser;
    // End of variables declaration//GEN-END:variables

    //Funcion para setear values iniciales.
    public void setValues(){
        jLabelUser.setText(MainMenu.Player1.username);
        jLabelPuntos.setText("" + MainMenu.Player1.puntos);
        jLabelPartidas.setText("" + MainMenu.Player1.partidas);
        jLabelMordor.setText("" + MainMenu.Player1.fuerzaMal);
        jLabelGondor.setText("" + MainMenu.Player1.fuerzaBien);
        jLabel10Partida.setText(MainMenu.Player1.Ultimos10.get(0));
        jLabel9Partida.setText(MainMenu.Player1.Ultimos10.get(1));
        jLabel8Partida.setText(MainMenu.Player1.Ultimos10.get(2));
        jLabel7Partida.setText(MainMenu.Player1.Ultimos10.get(3));
        jLabel6Partida.setText(MainMenu.Player1.Ultimos10.get(4));
        jLabel5Partida.setText(MainMenu.Player1.Ultimos10.get(5));
        jLabel4Partida.setText(MainMenu.Player1.Ultimos10.get(6));
        jLabel3Partida.setText(MainMenu.Player1.Ultimos10.get(7));
        jLabel2Partida.setText(MainMenu.Player1.Ultimos10.get(8));
        jLabel1Partida.setText(MainMenu.Player1.Ultimos10.get(9));
    }

}
