/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

/**
 *
 * @author Roberto Melara
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWarning = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUTitulo = new javax.swing.JLabel();
        jLabelPTitulo = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelSignUp = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWarning.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(174, 153, 108));
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 740, 50));

        jLabelTitulo.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(174, 153, 108));
        jLabelTitulo.setText("LOTR  Stratego");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabelUTitulo.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelUTitulo.setForeground(new java.awt.Color(174, 153, 108));
        jLabelUTitulo.setText("Usuario");
        getContentPane().add(jLabelUTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabelPTitulo.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelPTitulo.setForeground(new java.awt.Color(174, 153, 108));
        jLabelPTitulo.setText("Password");
        getContentPane().add(jLabelPTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 30));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 140, 30));

        jLabelSignUp.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelSignUp.setForeground(new java.awt.Color(174, 153, 108));
        jLabelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignUp.setText("Sign Up");
        jLabelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSignUpMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 400, 190, 190));

        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roberto Melara\\Downloads\\SignUp.png")); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignUpMousePressed
        for(Player player: Player.Usuarios){
            if(player.username.equals(jTextFieldUsuario.getText())){
                jLabelWarning.setText("Este nombre de usuario ya existe, porfavor elija uno nuevo.");
            }
        }
            if(jPasswordFieldPassword.getText().length()<5){
                jLabelWarning.setText("Password demasiado corto, el password debe contener exactamente 5 caracteres.");
            }else if(jPasswordFieldPassword.getText().length()>5){
                jLabelWarning.setText("Password demasiado largo, el password debe contener exactamente 5 caracteres.");
            }else{
                Player usuario = new Player(jTextFieldUsuario.getText(),jPasswordFieldPassword.getText());
                Player.Usuarios.add(usuario);
            }
    }//GEN-LAST:event_jLabelSignUpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPTitulo;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUTitulo;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
