/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Melara
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelSignUp = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelWarning = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(756, 732));
        setMinimumSize(new java.awt.Dimension(756, 732));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(174, 153, 108));
        jLabelTitle.setText("LOTR  Stratego");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelSignUp.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabelSignUp.setForeground(new java.awt.Color(174, 153, 108));
        jLabelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignUp.setText("SignUp");
        jLabelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSignUpMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 210, 210));

        jLabelUser.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(174, 153, 108));
        jLabelUser.setText("Username:");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(174, 153, 108));
        jLabelPassword.setText("Password:");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, 30));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, 30));

        jLabelWarning.setFont(new java.awt.Font("Ringbearer", 0, 16)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(174, 153, 108));
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 650, 750, 40));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/VisualAssets/SignUp.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignUpMousePressed
       
        MainMenu main = new MainMenu();
       
        
        if(jTextFieldUsername.getText().isEmpty() || jPasswordFieldPassword.getPassword().length==0){ 
            JOptionPane.showMessageDialog(null, "No pueden haber casillas en blanco!!");                          
        }else{ 
        
        for(Player player: Player.Usuarios)
            if(jTextFieldUsername.getText().equals(player.username)){
                JOptionPane.showMessageDialog (null, "Este nombre de usuario ya existe, porfavor ingrese uno nuevo.", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);    
                
                jTextFieldUsername.setText("");
                jPasswordFieldPassword.setText(null);
                main.setVisible(true);
                this.dispose();
                
                return;               
            }
        if(jPasswordFieldPassword.getPassword().length<5){
            
             jLabelWarning.setText("Password demasiado corto. El password debe contener exactamente 5 caracteres.");
             jPasswordFieldPassword.setText("");
             
        }else if(jPasswordFieldPassword.getPassword().length>5){
            
            jLabelWarning.setText("Password demasiado largo. El password debe contener exactamente 5 caracteres.");
            jPasswordFieldPassword.setText("");
                
        }else{             
            Player usuario = new Player(jTextFieldUsername.getText(),String.valueOf(jPasswordFieldPassword.getPassword()));
            JOptionPane.showMessageDialog (null, "Usuario Agregado", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
            Player.Usuarios.add(usuario);
                
            jTextFieldUsername.setText("");
            jPasswordFieldPassword.setText("");
            jLabelWarning.setText("");
                
             for(Player player: Player.Usuarios)
              System.out.println(player.username + " "+player.password);
            }
       }
      
    }//GEN-LAST:event_jLabelSignUpMousePressed
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
