/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

import java.io.IOException;

/**
 *
 * @author Roberto Melara
 */
public class SignInForm extends javax.swing.JFrame {

    /**
     * Creates new form SignInForm
     */
    public SignInForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelSignIn = new javax.swing.JLabel();
        jLabelWarning = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sign In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(18, 11, 11));
        jLabelTitle.setText("LOTR  Stratego");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelUser.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(174, 153, 108));
        jLabelUser.setText("Username");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(174, 153, 108));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, 30));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, 30));

        jLabelSignIn.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(174, 153, 108));
        jLabelSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignIn.setText("Sign In");
        jLabelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSignInMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 400, 210, 210));

        jLabelWarning.setFont(new java.awt.Font("Ringbearer", 0, 16)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(174, 153, 108));
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 750, 40));

        jLabelRegresar.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(174, 153, 108));
        jLabelRegresar.setText("Regresar");
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/SignIn.png"))); // NOI18N
        jLabelBackground.setDoubleBuffered(true);
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignInMousePressed
        try {
            //Extrae los datos de la Jframe.
            String usern = jTextFieldUsername.getText();
            String pass = jPasswordFieldPassword.getText();
            
            //Funcion para el manejo de excepciones en el signIn.
            if(Player.signIn(usern, pass) == 0){
                MainMenu.Player1 = Player.cargarDatos(usern);
                MainMenu mp = new MainMenu();
                mp.setVisible(true);
                jTextFieldUsername.setText("");
                jPasswordFieldPassword.setText(null);
                this.dispose();
            }else if(Player.signIn(usern, pass) == 1){
                jLabelWarning.setText("Usuario no encontrado.");
            }else if(Player.signIn(usern, pass) == 2){
                jLabelWarning.setText("Password Incorrecta.");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabelSignInMousePressed

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        // Regresar al menu inicio.
        Inicio init = new Inicio();
        init.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegresarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUser;
    public static javax.swing.JLabel jLabelWarning;
    public static javax.swing.JPasswordField jPasswordFieldPassword;
    public static javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
