/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

import Fichas.Ficha;
import java.util.ArrayList;
import javax.swing.ImageIcon;


/**
 *
 * @author Roberto Melara
 */
public final class TableroVisual extends javax.swing.JFrame {
    //Creacion de objeto tipo Tablero.
    public static Tablero Game = new Tablero();
    //Contador de turnos.
    int turno = 0;
    //Contadores estadisticos.
    int piezasGondor = 0;
    int piezasMordor = 0;
    //Array para manejar el log.
    ArrayList<String> log = new ArrayList<>();
         
    /**
     * Creates new form TableroVisual
     */
    public TableroVisual() {
        initComponents();
        this.setExtendedState(getExtendedState());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPos07 = new javax.swing.JLabel();
        jLabelPos02 = new javax.swing.JLabel();
        jLabelPos03 = new javax.swing.JLabel();
        jLabelPos04 = new javax.swing.JLabel();
        jLabelPos05 = new javax.swing.JLabel();
        jLabelPos06 = new javax.swing.JLabel();
        jLabelPos00 = new javax.swing.JLabel();
        jLabelPos08 = new javax.swing.JLabel();
        jLabelPos09 = new javax.swing.JLabel();
        jLabelPos01 = new javax.swing.JLabel();
        jLabelPos17 = new javax.swing.JLabel();
        jLabelPos12 = new javax.swing.JLabel();
        jLabelPos13 = new javax.swing.JLabel();
        jLabelPos14 = new javax.swing.JLabel();
        jLabelPos15 = new javax.swing.JLabel();
        jLabelPos16 = new javax.swing.JLabel();
        jLabelPos10 = new javax.swing.JLabel();
        jLabelPos18 = new javax.swing.JLabel();
        jLabelPos19 = new javax.swing.JLabel();
        jLabelPos11 = new javax.swing.JLabel();
        jLabelPos27 = new javax.swing.JLabel();
        jLabelPos22 = new javax.swing.JLabel();
        jLabelPos23 = new javax.swing.JLabel();
        jLabelPos24 = new javax.swing.JLabel();
        jLabelPos25 = new javax.swing.JLabel();
        jLabelPos26 = new javax.swing.JLabel();
        jLabelPos20 = new javax.swing.JLabel();
        jLabelPos28 = new javax.swing.JLabel();
        jLabelPos29 = new javax.swing.JLabel();
        jLabelPos21 = new javax.swing.JLabel();
        jLabelPos30 = new javax.swing.JLabel();
        jLabelPos31 = new javax.swing.JLabel();
        jLabelPos32 = new javax.swing.JLabel();
        jLabelPos33 = new javax.swing.JLabel();
        jLabelPos34 = new javax.swing.JLabel();
        jLabelPos35 = new javax.swing.JLabel();
        jLabelPos36 = new javax.swing.JLabel();
        jLabelPos37 = new javax.swing.JLabel();
        jLabelPos38 = new javax.swing.JLabel();
        jLabelPos39 = new javax.swing.JLabel();
        jLabelPos40 = new javax.swing.JLabel();
        jLabelPos41 = new javax.swing.JLabel();
        jLabelPos44 = new javax.swing.JLabel();
        jLabelPos45 = new javax.swing.JLabel();
        jLabelPos48 = new javax.swing.JLabel();
        jLabelPos49 = new javax.swing.JLabel();
        jLabelPos50 = new javax.swing.JLabel();
        jLabelPos51 = new javax.swing.JLabel();
        jLabelPos54 = new javax.swing.JLabel();
        jLabelPos55 = new javax.swing.JLabel();
        jLabelPos58 = new javax.swing.JLabel();
        jLabelPos59 = new javax.swing.JLabel();
        jLabelPos60 = new javax.swing.JLabel();
        jLabelPos61 = new javax.swing.JLabel();
        jLabelPos62 = new javax.swing.JLabel();
        jLabelPos63 = new javax.swing.JLabel();
        jLabelPos64 = new javax.swing.JLabel();
        jLabelPos65 = new javax.swing.JLabel();
        jLabelPos66 = new javax.swing.JLabel();
        jLabelPos67 = new javax.swing.JLabel();
        jLabelPos68 = new javax.swing.JLabel();
        jLabelPos69 = new javax.swing.JLabel();
        jLabelPos70 = new javax.swing.JLabel();
        jLabelPos71 = new javax.swing.JLabel();
        jLabelPos72 = new javax.swing.JLabel();
        jLabelPos73 = new javax.swing.JLabel();
        jLabelPos74 = new javax.swing.JLabel();
        jLabelPos75 = new javax.swing.JLabel();
        jLabelPos76 = new javax.swing.JLabel();
        jLabelPos77 = new javax.swing.JLabel();
        jLabelPos78 = new javax.swing.JLabel();
        jLabelPos79 = new javax.swing.JLabel();
        jLabelPos80 = new javax.swing.JLabel();
        jLabelPos81 = new javax.swing.JLabel();
        jLabelPos82 = new javax.swing.JLabel();
        jLabelPos83 = new javax.swing.JLabel();
        jLabelPos84 = new javax.swing.JLabel();
        jLabelPos85 = new javax.swing.JLabel();
        jLabelPos86 = new javax.swing.JLabel();
        jLabelPos87 = new javax.swing.JLabel();
        jLabelPos88 = new javax.swing.JLabel();
        jLabelPos89 = new javax.swing.JLabel();
        jLabelPos90 = new javax.swing.JLabel();
        jLabelPos91 = new javax.swing.JLabel();
        jLabelPos92 = new javax.swing.JLabel();
        jLabelPos93 = new javax.swing.JLabel();
        jLabelPos94 = new javax.swing.JLabel();
        jLabelPos95 = new javax.swing.JLabel();
        jLabelPos96 = new javax.swing.JLabel();
        jLabelPos97 = new javax.swing.JLabel();
        jLabelPos98 = new javax.swing.JLabel();
        jLabelPos99 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelPlayer = new javax.swing.JLabel();
        jLabelPrevia = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldFilaInit = new javax.swing.JTextField();
        jTextFieldColumnaInit = new javax.swing.JTextField();
        jTextFieldFilaFin = new javax.swing.JTextField();
        jTextFieldColumnaFin = new javax.swing.JTextField();
        jButtonBuscarPieza = new javax.swing.JButton();
        jButtonMover = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPos07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos07.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos07.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos07.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos07, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jLabelPos02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos02.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos02.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos02.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos02, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabelPos03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos03.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos03.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos03.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos03, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jLabelPos04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos04.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos04.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos04.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos04, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        jLabelPos05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos05.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos05.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos05.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos05, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        jLabelPos06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos06.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos06.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos06.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos06, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jLabelPos00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos00.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos00.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos00.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos00, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabelPos08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos08.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos08.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos08.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos08, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        jLabelPos09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos09.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos09.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos09.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos09, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jLabelPos01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos01.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos01.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos01.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos01, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabelPos17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos17.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos17.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos17.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));

        jLabelPos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos12.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos12.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos12.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jLabelPos13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos13.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos13.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos13.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabelPos14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos14.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos14.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos14.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabelPos15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos15.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos15.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos15.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        jLabelPos16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos16.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos16.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos16.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        jLabelPos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos10.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos10.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos10.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabelPos18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos18.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos18.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos18.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos18, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, -1));

        jLabelPos19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos19.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos19.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos19.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos19, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, -1, -1));

        jLabelPos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos11.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos11.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos11.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabelPos27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos27.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos27.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos27.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, -1, -1));

        jLabelPos22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos22.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos22.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos22.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabelPos23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos23.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos23.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos23.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jLabelPos24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos24.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos24.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos24.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabelPos25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos25.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos25.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos25.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        jLabelPos26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos26.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos26.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos26.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos26, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        jLabelPos20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos20.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos20.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos20.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabelPos28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos28.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos28.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos28.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos28, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        jLabelPos29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos29.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos29.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos29.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos29, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, -1, -1));

        jLabelPos21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos21.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos21.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos21.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabelPos30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos30.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos30.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos30.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabelPos31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos31.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos31.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos31.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabelPos32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos32.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos32.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos32.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabelPos33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos33.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos33.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos33.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jLabelPos34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos34.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos34.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos34.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos34, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jLabelPos35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos35.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos35.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos35.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos35, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabelPos36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos36.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos36.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos36.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos36, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jLabelPos37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos37.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos37.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos37.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos37, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jLabelPos38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos38.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos38.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos38.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos38, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        jLabelPos39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos39.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos39.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos39.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos39, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, -1, -1));

        jLabelPos40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos40.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos40.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos40.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jLabelPos41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos41.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos41.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos41.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos41, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabelPos44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos44.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos44.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos44.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos44, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        jLabelPos45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos45.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos45.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos45.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos45, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jLabelPos48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos48.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos48.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos48.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos48, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, -1, -1));

        jLabelPos49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos49.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos49.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos49.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos49, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, -1, -1));

        jLabelPos50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos50.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos50.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos50.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jLabelPos51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos51.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos51.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos51.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos51, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabelPos54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos54.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos54.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos54.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos54, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jLabelPos55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos55.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos55.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos55.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos55, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        jLabelPos58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos58.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos58.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos58.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos58, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, -1));

        jLabelPos59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos59.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos59.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos59.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos59, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));

        jLabelPos60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos60.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos60.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos60.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos60, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jLabelPos61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos61.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos61.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos61.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos61, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabelPos62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos62.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos62.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos62.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos62, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabelPos63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos63.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos63.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos63.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos63, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jLabelPos64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos64.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos64.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos64.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos64, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        jLabelPos65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos65.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos65.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos65.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos65, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jLabelPos66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos66.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos66.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos66.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos66, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, -1, -1));

        jLabelPos67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos67.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos67.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos67.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos67, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        jLabelPos68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos68.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos68.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos68.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos68, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, -1, -1));

        jLabelPos69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos69.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos69.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos69.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos69, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, -1));

        jLabelPos70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos70.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos70.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos70.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        jLabelPos71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos71.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos71.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos71.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos71, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        jLabelPos72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos72.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos72.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos72.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos72, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        jLabelPos73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos73.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos73.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos73.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos73, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        jLabelPos74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos74.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos74.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos74.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos74, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        jLabelPos75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos75.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos75.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos75.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos75, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        jLabelPos76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos76.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos76.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos76.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos76, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));

        jLabelPos77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos77.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos77.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos77.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos77, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, -1, -1));

        jLabelPos78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos78.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos78.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos78.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos78, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, -1, -1));

        jLabelPos79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos79.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos79.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos79.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos79, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, -1, -1));

        jLabelPos80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos80.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos80.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos80.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos80, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        jLabelPos81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos81.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos81.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos81.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos81, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        jLabelPos82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos82.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos82.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos82.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos82, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, -1, -1));

        jLabelPos83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos83.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos83.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos83.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos83, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, -1, -1));

        jLabelPos84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos84.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos84.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos84.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos84, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, -1, -1));

        jLabelPos85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos85.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos85.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos85.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos85, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, -1));

        jLabelPos86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos86.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos86.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos86.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos86, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        jLabelPos87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos87.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos87.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos87.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos87, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, -1, -1));

        jLabelPos88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos88.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos88.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos88.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos88, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, -1, -1));

        jLabelPos89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos89.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos89.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos89.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos89, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, -1, -1));

        jLabelPos90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos90.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos90.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos90.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos90, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, -1, -1));

        jLabelPos91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos91.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos91.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos91.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos91, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, -1, -1));

        jLabelPos92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos92.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos92.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos92.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos92, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, -1, -1));

        jLabelPos93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos93.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos93.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos93.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos93, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, -1, -1));

        jLabelPos94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos94.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos94.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos94.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos94, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, -1, -1));

        jLabelPos95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos95.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos95.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos95.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos95, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 690, -1, -1));

        jLabelPos96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos96.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos96.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos96.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos96, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, -1, -1));

        jLabelPos97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos97.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos97.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos97.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos97, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 690, -1, -1));

        jLabelPos98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos98.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos98.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos98.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos98, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 690, -1, -1));

        jLabelPos99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Default.png"))); // NOI18N
        jLabelPos99.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPos99.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPos99.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPos99, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 690, -1, -1));

        jButton1.setText("Iniciar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabelPlayer.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelPlayer.setForeground(new java.awt.Color(174, 153, 108));
        jLabelPlayer.setText("Player #");
        getContentPane().add(jLabelPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, 160, -1));

        jLabelPrevia.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelPrevia.setForeground(new java.awt.Color(174, 153, 108));
        jLabelPrevia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrevia.setMaximumSize(new java.awt.Dimension(76, 76));
        jLabelPrevia.setMinimumSize(new java.awt.Dimension(76, 76));
        jLabelPrevia.setPreferredSize(new java.awt.Dimension(76, 76));
        getContentPane().add(jLabelPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 150, 80, 80));

        jLabelName.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(174, 153, 108));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 190, 30));
        getContentPane().add(jTextFieldFilaInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 30, 30));
        getContentPane().add(jTextFieldColumnaInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 350, 30, 30));
        getContentPane().add(jTextFieldFilaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 470, 30, 30));
        getContentPane().add(jTextFieldColumnaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 470, 30, 30));

        jButtonBuscarPieza.setText("Buscar Pieza");
        jButtonBuscarPieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscarPiezaMousePressed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, -1, 20));

        jButtonMover.setText("Mover");
        jButtonMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMoverMousePressed(evt);
            }
        });
        getContentPane().add(jButtonMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 510, -1, 20));

        jLabel5.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(174, 153, 108));
        jLabel5.setText("Fila");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(174, 153, 108));
        jLabel6.setText("Columna");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(174, 153, 108));
        jLabel7.setText("Fila");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ringbearer", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(174, 153, 108));
        jLabel8.setText("Columna");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 440, -1, -1));

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 560, 220, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roberto Melara\\Downloads\\Proyect References\\Abandonar.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roberto Melara\\Downloads\\TableroVisual.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Game.construirTablero(Game);
        ActualizarTablero();
        jButton1.disable();
        jButton1.hide();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButtonBuscarPiezaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarPiezaMousePressed
        int c = Integer.parseInt(jTextFieldColumnaInit.getText());
        int f = Integer.parseInt(jTextFieldFilaInit.getText());
        if(turno%2==0){
            if(Game.Tablero[f][c].getFaccion() == 1){
                jLabelPrevia.setIcon(Game.Tablero[f][c].getPrevia());
                jLabelName.setText(Game.Tablero[f][c].getNombre());
            }else{
                jTextAreaLog.append("\n Advertencia: Pieza no es tuya!");
            }
        }else{
           if(Game.Tablero[f][c].getFaccion() == 2){
                jLabelPrevia.setIcon(Game.Tablero[f][c].getPrevia());
                jLabelName.setText(Game.Tablero[f][c].getNombre());
            }else{
                jTextAreaLog.append("\n Advertencia: Pieza no es tuya!");
            } 
        }
    }//GEN-LAST:event_jButtonBuscarPiezaMousePressed

    private void jButtonMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMoverMousePressed
        int f1 = Integer.parseInt(jTextFieldFilaInit.getText());
        int c1 = Integer.parseInt(jTextFieldColumnaInit.getText());
        int f = Integer.parseInt(jTextFieldFilaFin.getText());
        int c = Integer.parseInt(jTextFieldColumnaFin.getText());
        if(turno % 2 == 0){
            if(Game.Tablero[f1][c1].getFaccion() == 1){
                if(c1 == c || f1 == f){
                    if(f1-f == 1 || f-f1 == 1 || c-c1 == 1 || c1-c == 1){
                        if(Game.Tablero[f][c].getFaccion() == 0){
                            Game.Tablero[f][c] = Game.Tablero[f1][c1];
                            Game.Tablero[f1][c1] = new Ficha();
                            jTextAreaLog.append("\n Movimiento Exitoso.");
                            turno ++;
                            ActualizarTablero();
                        }else if(Game.Tablero[f][c].getFaccion() == 2){
                            Game.Tablero[f][c] = Game.Tablero[f1][c1];
                            Game.Tablero[f1][c1] = new Ficha();
                            jTextAreaLog.append("\n Has derrotado a una unidad enemiga.");
                            turno ++;
                            ActualizarTablero();
                        }else if(Game.Tablero[f][c].getFaccion() == 1){
                            jTextAreaLog.append("\n Posicion ocupada por una unidad tuya.");
                        }
                    }
                }
            }
        }else{
            if(Game.Tablero[f1][c1].getFaccion() == 2){
                if(c1 == c || f1 == f){
                    if(f1-f == 1 || f-f1 == 1 || c-c1 == 1 || c1-c == 1){
                        if(Game.Tablero[f][c].getFaccion() == 0){
                            Game.Tablero[f][c] = Game.Tablero[f1][c1];
                            Game.Tablero[f1][c1] = new Ficha();
                            jTextAreaLog.append("\n Movimiento Exitoso.");
                            turno ++;
                            ActualizarTablero();
                        }else if(Game.Tablero[f][c].getFaccion() == 1){
                            Game.Tablero[f][c] = Game.Tablero[f1][c1];
                            Game.Tablero[f1][c1] = new Ficha();
                            jTextAreaLog.append("\n Has derrotado a una unidad enemiga.");
                            turno ++;
                            ActualizarTablero();
                        }else if(Game.Tablero[f][c].getFaccion() == 2){
                            jTextAreaLog.append("\n Posicion ocupada por una unidad tuya.");
                        }
                    }
                }
            } 
        }
    }//GEN-LAST:event_jButtonMoverMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroVisual().setVisible(true);
            }
        });
        
        
    }
    //Funcion para actualizar el tablero entero.
    public void ActualizarTablero(){
        fila0();
        fila1();
        fila2();
        fila3();
        fila4();
        fila5();
        fila6();
        fila7();
        fila8();
        fila9();
        actualizarTableroLateral();
    }
    
    //Funciones para Actualizar las filas (Graficos).
    public void fila0(){
        jLabelPos00.setIcon(Game.Tablero[0][0].getIcono());
        jLabelPos01.setIcon(Game.Tablero[0][1].getIcono());
        jLabelPos02.setIcon(Game.Tablero[0][2].getIcono());
        jLabelPos03.setIcon(Game.Tablero[0][3].getIcono());
        jLabelPos04.setIcon(Game.Tablero[0][4].getIcono());
        jLabelPos05.setIcon(Game.Tablero[0][5].getIcono());
        jLabelPos06.setIcon(Game.Tablero[0][6].getIcono());
        jLabelPos07.setIcon(Game.Tablero[0][7].getIcono());
        jLabelPos08.setIcon(Game.Tablero[0][8].getIcono());
        jLabelPos09.setIcon(Game.Tablero[0][9].getIcono());
    }
    public void fila1(){
        jLabelPos10.setIcon(Game.Tablero[1][0].getIcono());
        jLabelPos11.setIcon(Game.Tablero[1][1].getIcono());
        jLabelPos12.setIcon(Game.Tablero[1][2].getIcono());
        jLabelPos13.setIcon(Game.Tablero[1][3].getIcono());
        jLabelPos14.setIcon(Game.Tablero[1][4].getIcono());
        jLabelPos15.setIcon(Game.Tablero[1][5].getIcono());
        jLabelPos16.setIcon(Game.Tablero[1][6].getIcono());
        jLabelPos17.setIcon(Game.Tablero[1][7].getIcono());
        jLabelPos18.setIcon(Game.Tablero[1][8].getIcono());
        jLabelPos19.setIcon(Game.Tablero[1][9].getIcono());
    }
    public void fila2(){
        jLabelPos20.setIcon(Game.Tablero[2][0].getIcono());
        jLabelPos21.setIcon(Game.Tablero[2][1].getIcono());
        jLabelPos22.setIcon(Game.Tablero[2][2].getIcono());
        jLabelPos23.setIcon(Game.Tablero[2][3].getIcono());
        jLabelPos24.setIcon(Game.Tablero[2][4].getIcono());
        jLabelPos25.setIcon(Game.Tablero[2][5].getIcono());
        jLabelPos26.setIcon(Game.Tablero[2][6].getIcono());
        jLabelPos27.setIcon(Game.Tablero[2][7].getIcono());
        jLabelPos28.setIcon(Game.Tablero[2][8].getIcono());
        jLabelPos29.setIcon(Game.Tablero[2][9].getIcono());
    }
    public void fila3(){
        jLabelPos30.setIcon(Game.Tablero[3][0].getIcono());
        jLabelPos31.setIcon(Game.Tablero[3][1].getIcono());
        jLabelPos32.setIcon(Game.Tablero[3][2].getIcono());
        jLabelPos33.setIcon(Game.Tablero[3][3].getIcono());
        jLabelPos34.setIcon(Game.Tablero[3][4].getIcono());
        jLabelPos35.setIcon(Game.Tablero[3][5].getIcono());
        jLabelPos36.setIcon(Game.Tablero[3][6].getIcono());
        jLabelPos37.setIcon(Game.Tablero[3][7].getIcono());
        jLabelPos38.setIcon(Game.Tablero[3][8].getIcono());
        jLabelPos39.setIcon(Game.Tablero[3][9].getIcono());
    }
    public void fila4(){
        jLabelPos40.setIcon(Game.Tablero[4][0].getIcono());
        jLabelPos41.setIcon(Game.Tablero[4][1].getIcono());
        jLabelPos44.setIcon(Game.Tablero[4][4].getIcono());
        jLabelPos45.setIcon(Game.Tablero[4][5].getIcono());
        jLabelPos48.setIcon(Game.Tablero[4][8].getIcono());
        jLabelPos49.setIcon(Game.Tablero[4][9].getIcono());
    }
    public void fila5(){
        jLabelPos50.setIcon(Game.Tablero[5][0].getIcono());
        jLabelPos51.setIcon(Game.Tablero[5][1].getIcono());
        jLabelPos54.setIcon(Game.Tablero[5][4].getIcono());
        jLabelPos55.setIcon(Game.Tablero[5][5].getIcono());
        jLabelPos58.setIcon(Game.Tablero[5][8].getIcono());
        jLabelPos59.setIcon(Game.Tablero[5][9].getIcono());
    }
    public void fila6(){
        jLabelPos60.setIcon(Game.Tablero[6][0].getIcono());
        jLabelPos61.setIcon(Game.Tablero[6][1].getIcono());
        jLabelPos62.setIcon(Game.Tablero[6][2].getIcono());
        jLabelPos63.setIcon(Game.Tablero[6][3].getIcono());
        jLabelPos64.setIcon(Game.Tablero[6][4].getIcono());
        jLabelPos65.setIcon(Game.Tablero[6][5].getIcono());
        jLabelPos66.setIcon(Game.Tablero[6][6].getIcono());
        jLabelPos67.setIcon(Game.Tablero[6][7].getIcono());
        jLabelPos68.setIcon(Game.Tablero[6][8].getIcono());
        jLabelPos69.setIcon(Game.Tablero[6][9].getIcono());
    }   
    public void fila7(){
        jLabelPos70.setIcon(Game.Tablero[7][0].getIcono());
        jLabelPos71.setIcon(Game.Tablero[7][1].getIcono());
        jLabelPos72.setIcon(Game.Tablero[7][2].getIcono());
        jLabelPos73.setIcon(Game.Tablero[7][3].getIcono());
        jLabelPos74.setIcon(Game.Tablero[7][4].getIcono());
        jLabelPos75.setIcon(Game.Tablero[7][5].getIcono());
        jLabelPos76.setIcon(Game.Tablero[7][6].getIcono());
        jLabelPos77.setIcon(Game.Tablero[7][7].getIcono());
        jLabelPos78.setIcon(Game.Tablero[7][8].getIcono());
        jLabelPos79.setIcon(Game.Tablero[7][9].getIcono());
    }
    public void fila8(){
        jLabelPos80.setIcon(Game.Tablero[8][0].getIcono());
        jLabelPos81.setIcon(Game.Tablero[8][1].getIcono());
        jLabelPos82.setIcon(Game.Tablero[8][2].getIcono());
        jLabelPos83.setIcon(Game.Tablero[8][3].getIcono());
        jLabelPos84.setIcon(Game.Tablero[8][4].getIcono());
        jLabelPos85.setIcon(Game.Tablero[8][5].getIcono());
        jLabelPos86.setIcon(Game.Tablero[8][6].getIcono());
        jLabelPos87.setIcon(Game.Tablero[8][7].getIcono());
        jLabelPos88.setIcon(Game.Tablero[8][8].getIcono());
        jLabelPos89.setIcon(Game.Tablero[8][9].getIcono());
    }
    public void fila9(){
        jLabelPos90.setIcon(Game.Tablero[9][0].getIcono());
        jLabelPos91.setIcon(Game.Tablero[9][1].getIcono());
        jLabelPos92.setIcon(Game.Tablero[9][2].getIcono());
        jLabelPos93.setIcon(Game.Tablero[9][3].getIcono());
        jLabelPos94.setIcon(Game.Tablero[9][4].getIcono());
        jLabelPos95.setIcon(Game.Tablero[9][5].getIcono());
        jLabelPos96.setIcon(Game.Tablero[9][6].getIcono());
        jLabelPos97.setIcon(Game.Tablero[9][7].getIcono());
        jLabelPos98.setIcon(Game.Tablero[9][8].getIcono());
        jLabelPos99.setIcon(Game.Tablero[9][9].getIcono());
    }
    
    //Actualizar Tablero Lateral.
    public void actualizarTableroLateral(){
        if(turno %2 == 0){
            jLabelPlayer.setText("Player 1");
        }else{
            jLabelPlayer.setText("Player 2");
        }
        jLabelName.setText("");
        jLabelPrevia.setIcon(new ImageIcon("Fichas/Vacio.png"));
        jTextFieldColumnaFin.setText(null);
        jTextFieldColumnaInit.setText(null);
        jTextFieldFilaInit.setText(null);
        jTextFieldFilaFin.setText(null);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarPieza;
    private javax.swing.JButton jButtonMover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPlayer;
    private javax.swing.JLabel jLabelPos00;
    private javax.swing.JLabel jLabelPos01;
    private javax.swing.JLabel jLabelPos02;
    private javax.swing.JLabel jLabelPos03;
    private javax.swing.JLabel jLabelPos04;
    private javax.swing.JLabel jLabelPos05;
    private javax.swing.JLabel jLabelPos06;
    private javax.swing.JLabel jLabelPos07;
    private javax.swing.JLabel jLabelPos08;
    private javax.swing.JLabel jLabelPos09;
    private javax.swing.JLabel jLabelPos10;
    private javax.swing.JLabel jLabelPos11;
    private javax.swing.JLabel jLabelPos12;
    private javax.swing.JLabel jLabelPos13;
    private javax.swing.JLabel jLabelPos14;
    private javax.swing.JLabel jLabelPos15;
    private javax.swing.JLabel jLabelPos16;
    private javax.swing.JLabel jLabelPos17;
    private javax.swing.JLabel jLabelPos18;
    private javax.swing.JLabel jLabelPos19;
    private javax.swing.JLabel jLabelPos20;
    private javax.swing.JLabel jLabelPos21;
    private javax.swing.JLabel jLabelPos22;
    private javax.swing.JLabel jLabelPos23;
    private javax.swing.JLabel jLabelPos24;
    private javax.swing.JLabel jLabelPos25;
    private javax.swing.JLabel jLabelPos26;
    private javax.swing.JLabel jLabelPos27;
    private javax.swing.JLabel jLabelPos28;
    private javax.swing.JLabel jLabelPos29;
    private javax.swing.JLabel jLabelPos30;
    private javax.swing.JLabel jLabelPos31;
    private javax.swing.JLabel jLabelPos32;
    private javax.swing.JLabel jLabelPos33;
    private javax.swing.JLabel jLabelPos34;
    private javax.swing.JLabel jLabelPos35;
    private javax.swing.JLabel jLabelPos36;
    private javax.swing.JLabel jLabelPos37;
    private javax.swing.JLabel jLabelPos38;
    private javax.swing.JLabel jLabelPos39;
    private javax.swing.JLabel jLabelPos40;
    private javax.swing.JLabel jLabelPos41;
    private javax.swing.JLabel jLabelPos44;
    private javax.swing.JLabel jLabelPos45;
    private javax.swing.JLabel jLabelPos48;
    private javax.swing.JLabel jLabelPos49;
    private javax.swing.JLabel jLabelPos50;
    private javax.swing.JLabel jLabelPos51;
    private javax.swing.JLabel jLabelPos54;
    private javax.swing.JLabel jLabelPos55;
    private javax.swing.JLabel jLabelPos58;
    private javax.swing.JLabel jLabelPos59;
    private javax.swing.JLabel jLabelPos60;
    private javax.swing.JLabel jLabelPos61;
    private javax.swing.JLabel jLabelPos62;
    private javax.swing.JLabel jLabelPos63;
    private javax.swing.JLabel jLabelPos64;
    private javax.swing.JLabel jLabelPos65;
    private javax.swing.JLabel jLabelPos66;
    private javax.swing.JLabel jLabelPos67;
    private javax.swing.JLabel jLabelPos68;
    private javax.swing.JLabel jLabelPos69;
    private javax.swing.JLabel jLabelPos70;
    private javax.swing.JLabel jLabelPos71;
    private javax.swing.JLabel jLabelPos72;
    private javax.swing.JLabel jLabelPos73;
    private javax.swing.JLabel jLabelPos74;
    private javax.swing.JLabel jLabelPos75;
    private javax.swing.JLabel jLabelPos76;
    private javax.swing.JLabel jLabelPos77;
    private javax.swing.JLabel jLabelPos78;
    private javax.swing.JLabel jLabelPos79;
    private javax.swing.JLabel jLabelPos80;
    private javax.swing.JLabel jLabelPos81;
    private javax.swing.JLabel jLabelPos82;
    private javax.swing.JLabel jLabelPos83;
    private javax.swing.JLabel jLabelPos84;
    private javax.swing.JLabel jLabelPos85;
    private javax.swing.JLabel jLabelPos86;
    private javax.swing.JLabel jLabelPos87;
    private javax.swing.JLabel jLabelPos88;
    private javax.swing.JLabel jLabelPos89;
    private javax.swing.JLabel jLabelPos90;
    private javax.swing.JLabel jLabelPos91;
    private javax.swing.JLabel jLabelPos92;
    private javax.swing.JLabel jLabelPos93;
    private javax.swing.JLabel jLabelPos94;
    private javax.swing.JLabel jLabelPos95;
    private javax.swing.JLabel jLabelPos96;
    private javax.swing.JLabel jLabelPos97;
    private javax.swing.JLabel jLabelPos98;
    private javax.swing.JLabel jLabelPos99;
    private javax.swing.JLabel jLabelPrevia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldColumnaFin;
    private javax.swing.JTextField jTextFieldColumnaInit;
    private javax.swing.JTextField jTextFieldFilaFin;
    private javax.swing.JTextField jTextFieldFilaInit;
    // End of variables declaration//GEN-END:variables
}
