/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego;

/**
 *
 * @author Roberto Melara
 */
public class TierraMedia extends javax.swing.JFrame {

    /**
     * Creates new form TierraMedia
     */
    public TierraMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelBatallas = new javax.swing.JLabel();
        jLabelRanking = new javax.swing.JLabel();
        jLabelBatallasTxt = new javax.swing.JLabel();
        jLabelRankingTxt = new javax.swing.JLabel();
        jLabelRegresarTxt = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Middle Earth");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTittle.setFont(new java.awt.Font("Ringbearer", 0, 48)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(185, 167, 129));
        jLabelTittle.setText("Middle Earth");
        getContentPane().add(jLabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelBatallas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Batallas.png"))); // NOI18N
        jLabelBatallas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBatallasMousePressed(evt);
            }
        });
        getContentPane().add(jLabelBatallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabelRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/Ranking.png"))); // NOI18N
        jLabelRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRankingMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabelBatallasTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelBatallasTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelBatallasTxt.setText("Batallas");
        getContentPane().add(jLabelBatallasTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabelRankingTxt.setFont(new java.awt.Font("Ringbearer", 0, 24)); // NOI18N
        jLabelRankingTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRankingTxt.setText("Ranking");
        getContentPane().add(jLabelRankingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jLabelRegresarTxt.setFont(new java.awt.Font("Ringbearer", 0, 36)); // NOI18N
        jLabelRegresarTxt.setForeground(new java.awt.Color(185, 167, 129));
        jLabelRegresarTxt.setText("Regresar");
        jLabelRegresarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarTxtMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/ElementosVisuales/TierraMedia.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBatallasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBatallasMousePressed
        //Ir al menu Batallas.
        Batallas bt = new Batallas();
        bt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBatallasMousePressed

    private void jLabelRegresarTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarTxtMousePressed
        //Regresar al menu principal
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegresarTxtMousePressed

    private void jLabelRankingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRankingMousePressed
        //Ir al ranking.
        Ranking r = new Ranking();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRankingMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TierraMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TierraMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TierraMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TierraMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TierraMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBatallas;
    private javax.swing.JLabel jLabelBatallasTxt;
    private javax.swing.JLabel jLabelRanking;
    private javax.swing.JLabel jLabelRankingTxt;
    private javax.swing.JLabel jLabelRegresarTxt;
    private javax.swing.JLabel jLabelTittle;
    // End of variables declaration//GEN-END:variables
}
