/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotr.stratego.MenuPrincipal;

/**
 *
 * @author samuelborjas
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modoTutorial = new javax.swing.JRadioButton();
        ModoClasico = new javax.swing.JRadioButton();
        cdmRegresar = new javax.swing.JButton();
        cmdRegresarMenuP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modoTutorial.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        modoTutorial.setForeground(new java.awt.Color(255, 255, 255));
        modoTutorial.setText("Modo Tutorial");
        getContentPane().add(modoTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        ModoClasico.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        ModoClasico.setForeground(new java.awt.Color(255, 255, 255));
        ModoClasico.setText("Modo Clasico");
        getContentPane().add(ModoClasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        cdmRegresar.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        cdmRegresar.setText("Regresar a Menu Principal");
        cdmRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(cdmRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 40));

        cmdRegresarMenuP.setFont(new java.awt.Font("Baskerville", 0, 36)); // NOI18N
        cmdRegresarMenuP.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegresarMenuP.setText("Configuracion");
        cmdRegresarMenuP.setToolTipText("");
        getContentPane().add(cmdRegresarMenuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotr/stratego/VisualAssets/misdatos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdmRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmRegresarActionPerformed
        this.dispose();
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
    }//GEN-LAST:event_cdmRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ModoClasico;
    private javax.swing.JButton cdmRegresar;
    private javax.swing.JLabel cmdRegresarMenuP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton modoTutorial;
    // End of variables declaration//GEN-END:variables
}
